sudo: true
language: node_js
node_js: "6"
os: osx  
osx_image: xcode8.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
    - npm install electron-prebuilt --save-dev
    - npm install electron-builder webpack
    - npm install
    - webpack
    - npm run build
    
script:
    - ./node_modules/.bin/build --config ./electron-builder.yml --mac

deploy:
  provider: releases
  api_key: "ec671fce07cffeb37038f88f61533a534bda80fa"
  file: "./dist/mac/testApp-1.0.0.dmg"
  skip_cleanup: true
  on:
    tags: true
