language: node_js
node_js:
  - "6"

# osx_image: xcode8.2
os: 
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

install:
    - npm install electron-prebuilt --save-dev
    - npm install electron-builder webpack
    - npm install
    - webpack
    - npm run build
    
script:
    - pwd
    - ls -la
    - ./node_modules/.bin/build --config ./electron-builder.yml --mac
