sudo: true
language: node_js
node_js: "6"
os: osx  
osx_image: xcode8.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
    - npm install electron-prebuilt --save-dev
    - npm install electron-builder webpack
    - npm install
    - webpack
    - npm run build
    
script:
    - ./node_modules/.bin/build --config ./electron-builder.yml --mac

env:
  global:
    - "FTP_USER=diablos"
    - "FTP_PASSWORD=diablos"
    
after_success:
  "curl --ftp-create-dirs -T ./dist/mac/testApp-1.0.0.dmg -u $FTP_USER:$FTP_PASSWORD ftp://005.3vftp.com/wisnuc"
