language: node_js
node_js: "6"
os: osx  
osx_image: xcode8.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - echo $TRAVIS_OS_NAME

install:
    - npm install electron-prebuilt --save-dev
    - npm install electron-builder webpack
    - npm install
    - webpack
    - npm run build
    
script:
    - ./node_modules/.bin/build --config ./electron-builder.yml --mac
    
after_success:
  - openssl aes-256-cbc -K $encrypted_2f7ac37d66dd_key -iv $encrypted_2f7ac37d66dd_iv
    -in deploy_key.enc -out deploy_key -d
  - chmod 400 deploy_key
  - eval `ssh-agent`
  - ssh-add deploy_key
  - echo 'ssh -o StrictHostKeyChecking=no $*' > ssh
  - chmod +x ssh
  - export GIT_SSH='./ssh'
  - git add -A && git commit -m "add my files"
  - git remote add deploy git@github.com:JiangWeiGitHub/wisnucAssistant.git
  - '[ "${TRAVIS_BRANCH}" = "master" ] && git push deploy master'
