TRAVIS_OS_NAME:
  - osx

osx_image: xcode8.2
language: node_js

node_js:
    - "node"
    - "6"

# before_install:
#   - brew update

install:
    - npm install electron-prebuilt --save-dev
    - npm install electron-builder webpack
    - npm install
    - webpack
    - npm run build
    
script:
    - pwd
    - ls -la
    - ./node_modules/.bin/build --config ./electron-builder.yml --mac
