language: node_js
node_js: "6"
os: osx  
osx_image: xcode8.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - echo $TRAVIS_OS_NAME

install:
    - npm install electron-prebuilt --save-dev
    - npm install electron-builder webpack
    - npm install
    - webpack
    - npm run build
    
script:
    - ./node_modules/.bin/build --config ./electron-builder.yml --mac
    
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy https://github.com/JiangWeiGitHub/wisnucAssistant.git
  - git push deploy
