sudo: true
language: node_js
node_js: "6"
os: osx  
osx_image: xcode8.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
    - npm install
    - ./node_modules/.bin/webpack -p
    - npm run build
    
script:
    - ./node_modules/.bin/build --config ./electron-builder.yml --mac

deploy:
  provider: releases
  api_key:
    secure: e6a8749b90b75e0b74bcdef0100f3115c9429a0a
  file: ./dist/mac/testApp-1.0.0.dmg
  skip_cleanup: true
  on:
    tags: true
#    repo: JiangWeiGitHub/wisnucAssistant
