language: node_js
osx_image: xcode8.2
node_js:
    - "node"
    - "6"
install:
##    - cd /
#    - mkdir git
#    - git clone https://github.com/wisnuc/fruitmix-desktop.git
#    - cd fruitmix-desktop
#    - git checkout transimission
    - npm install electron-prebuilt --save-dev
    - npm install electron-builder webpack
    - npm install
    - webpack
    - npm run build
script:
    - pwd
    - ls -la
    - ./node_modules/.bin/build --config ./electron-builder.yml --mac
