environment:
  nodejs_version: "6"
  skip_tags: true

#  appveyor_repo_tag: true
#  release: wisnucAssistant-v$(appveyor_build_version)
#  description: 'Release test'
#  provider: GitHub
#  artifact: ./dist/"testApp Setup 1.0.0.exe"
#  draft: false
#  prerelease: false
#  auth_token:
#    secure: 938a98c742afc2ca0094a500bc0d15487b861655

install:
  - npm install electron-prebuilt --save-dev
  - npm install electron-builder webpack
  - npm install
  - ./node_modules/.bin/webpack
  - npm run build

build_script:
#  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64 -p always
  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64

#build: off

test: off

deploy:
  - provider: GitHub
    name: JiangWeiGitHub
    auth_token:
      secure: QdifofgEHCVGeC1LMxhxWnKjxDZKwOruUhW/6JzrlXmthWnaZ8rU0oLut+f+8BO1
    on:
      branch: master
#      appveyor_repo_tag: true
    release: wisnucAssistant-v$(appveyor_build_version)
    description: 'Release test'
    artifact: ./dist/"testApp Setup 1.0.0.exe"
    draft: false
    prerelease: false
