environment:
  nodejs_version: "6"
  appveyor_repo_tag: true

install:
  - npm install electron-prebuilt --save-dev
  - npm install electron-builder webpack
  - npm install
  - ./node_modules/.bin/webpack
  - npm run build
  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64

# before_build:
#  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64
#  - ls ./dist -la
#  - ls ./dist/"testApp Setup 1.0.0.exe" -la
#  - mv ./dist/"testApp Setup 1.0.0.exe" ./dist/wisnucAssistent.exe

build: off

deploy:
  release: wisnucAssistant-v$(appveyor_build_version)
  description: 'Release test'
  provider: GitHub
  auth_token:
    secure: ec671fce07cffeb37038f88f61533a534bda80fa
  artifact: ./dist/"testApp Setup 1.0.0.exe"
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
