environment:
  nodejs_version: "6"
  skip_tags: true

install:
  - npm install electron-prebuilt --save-dev
  - npm install electron-builder electron-updater webpack
  - npm install
  - ./node_modules/.bin/webpack
  - npm run build

build: off

build_script:
  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64

test: off

artifacts:
  - path: ./dist/testApp*
    name: testApp

deploy:
  - provider: GitHub
    release: wisnucAssistant-v$(appveyor_build_version)
    description: 'Release test'
    
    artifact: testApp
    draft: false
    prerelease: false
    
    auth_token:
      secure: 'DhLexoyfZQBXUj5vkTdvqedXl1BYQZiRbimUxTRUh4vfI9Ek1n1K2IxN+JDpMU/E'
      
    on:
      branch: master
 #    appveyor_repo_tag: true
