environment:
  nodejs_version: "6"
  appveyor_repo_tag: true
  auth_token:
    secure: t74NxP2qvZZdRzl7wFI2IE/3/XFKyZV8KihQJDhOnrjgGSJarwjgn+B4rS82750r

install:
  - npm install electron-prebuilt --save-dev
  - npm install electron-builder webpack
  - npm install
  - ./node_modules/.bin/webpack
  - npm run build

build_script:
  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64

build: off

test: off

deploy:
  release: wisnucAssistant-v$(appveyor_build_version)
  description: 'Release test'
  provider: GitHub
  username: JiangWeiGitHub
#  auth_token:
#    secure: t74NxP2qvZZdRzl7wFI2IE/3/XFKyZV8KihQJDhOnrjgGSJarwjgn+B4rS82750r
  artifact: ./dist/"testApp Setup 1.0.0.exe"
  draft: false
  prerelease: false
