environment:
  nodejs_version: "6"
  appveyor_repo_tag: true

install:
  - npm install electron-prebuilt --save-dev
  - npm install electron-builder webpack
  - npm install
  - ./node_modules/.bin/webpack
  - npm run build

build_script:
  - ./node_modules/.bin/build --config ./electron-builder.yml --win --x64

build: off

test: off

deploy:
  release: wisnucAssistant-v$(appveyor_build_version)
  description: 'Release test'
  provider: GitHub
  username: JiangWeiGitHub
  auth_token:
    secure: 938a98c742afc2ca0094a500bc0d15487b861655
  artifact: ./dist/"testApp Setup 1.0.0.exe"
  draft: false
  prerelease: false
